name: App-Vorschlag
description: Eine App zur Aufnahme in die Liste vorschlagen
title: "[Vorschlag]: "
labels:
assignees:
  - schulle4u
body:
  - type: markdown
    attributes:
      value: |
        Hier kannst du eine neue App zur Aufnahme in die Liste vorschlagen.
  - type: input
    id: name
    attributes:
      label: App-Name
      description: Name der App, wie er im Store oder beim Entwickler angezeigt wird.
      placeholder:
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: App-URL
      description: Store-Link oder Entwickler-Homepage
      placeholder:
    validations:
      required: true
  - type: dropdown
    id: availability
    attributes:
      label: Verf체gbarkeit
      description: Zu welchen Lizenzbedingungen ist die App erh채ltlich?
      options:
        - Kostenlos
        - Kostenlos und Open Source
        - Kostenlos, werbefinanziert
        - Kostenlos, Werbung und In-App-K채ufe
        - Kostenlos, In-App-K채ufe
        - Kostenpflichtig
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Beschreibung
      description: Eine kurze Beschreibung der App, optional Bemerkungen zur Barrierefreiheit. 
      render:
