name: Link Checker

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * SUN'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check URLs
        uses: paramt/url-checker@master
        with:
          files: "README.md"
          blacklist: "LICENSE,www.radio-browser.info,Wetter.com,Pump.io,Radio.de,F-Droid.org,https://bearware.dk/?page_id=353"